[package]
name = "comp"
version = "0.20.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "comp"
path = "src/comp.rs"

[dependencies]
